blank_issues_enabled: false  # ë¹ˆ ì´ìŠˆ ìƒì„±ì„ ë§‰ì•„ ì–‘ì‹ ì¤€ìˆ˜ë¥¼ ê°•ì œí•©ë‹ˆë‹¤.
contact_links:
  - name: ğŸ’¬ ì§ˆë¬¸ ë° í† ë¡  (Questions & Discussions)
    url: https://github.com/graviton94/cjfsdatacollect/discussions
    about: ì½”ë“œì— ëŒ€í•œ ì§ˆë¬¸ì´ë‚˜ ì•„ì´ë””ì–´ í† ë¡ ì€ ì´ìŠˆ ëŒ€ì‹  ì´ê³³ì„ ì´ìš©í•´ì£¼ì„¸ìš”.
